---
version: 2
deploy:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "daily"
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
