#language: ruby
#addons:
#  apt:
#    packages:
#    - cmake
#    - time

#script:
#  - sleep 25
#  - echo 'OK'
language: ruby
#services:
#  - postgresql
#before_script:
#  - psql -c 'create database travis_ci_test;' -U postgres
#env:
#  global:
#    - secure: PPC38ppzVbEUxEp9JgQLhqQTt9LbZ+PhAbSgqqGl02uSqCbp1EYGun8YG1pAtYY4oBbpOX/9tC9Z55oztBWWA8FHmlPLB3w4npSZzwNjXxcBrlWQ9Hv4W1jCO7ZJxQvOOD9WbblyfJqNWvzZG5OIzdr36oAusPiYPnE3LgSYEHdtjK4Xj4fHyJX3lYY4TZVSGNhNV5Jt9muSVMspplSMLujpNQY7mG4hoILR5K64SNoE6uYXG43Mbhs6ZVPU1SzUB+xqh9hWpvE+RlaSQuDRvZxhyPH5BpkWNEsQrVutPoAcqoiZHUmjHeoXvCf9kcla4URpERwxB5YO3BYW/a5bYEk0HDC9VLy1EmH4NsePj4K5QMliT1QHJ2+tfmTVhPkNlI2jQnP8a6173+fJ5EuvaOjrCY+l4pqUIIBSLOuMdXn8yXKMUlxF7qk/SlnNis8NJWT2Vpa/GxsGseYx8aPWcolEXj7jdC8K8Jc9gdvaPMRaoQx2IDg7FUeAeEL/NmZ42Voidt9cQqzwtmHTO7ezjBrwMNb69URIpx+H7g6ZSnVhftSBcU1lM5THfUIga3JqElOt+Tv0VjySsqYdH39l4zcwV6TPnjnggqpIgRu6NNJD/60HUrOIp6fyvHkp8WrS/kGTVWI/1iZJ+dZdi+TBDzKRLtRriZqLKtOtAg54cOc=
deploy:
  provider: pages:git
  token: dYurVniuZ+hI8na8b26T5b9jRdTpjgd/X8x769QqvFhsTpUxKCwmyeBRneH5nxApQiSF3yWU5A3yrJJwnJ398xTCzS/FzRJOFMg3dqgpej2NqqhnKad4HIaDDMbYAVCVASosb69BgQUzbgFuf3uGBDO8so7B1FbtTHBd7sD2KbibAKu7VPvJ4ca6CUr4yRN2fiOsUOu3ftvYVW4LwG4CTj1JZP0NG32F82muspwoM49i/F9vtAHBAuxlU+9SmrJd6S7E09NJK3yya3uj+5eiQB1oIy23B4ANZrZkoEHzy3TSC2jyEQKLQUrQN4nbK/AqDGIiU/OByCYr/PN44Y3Qzi70br5q1cIZlg+fHObUhZ7Z+2kk6vzv+fUSACwV0rKzqKT85r3EPVcu7Jpdrr7R0pahMZ7ODyYeZO3H3D1kEwXsd3xugLxlWQt5H1Mr/4gFeG52MGUJOOq+A8vGhnuF4b63RG16izNLd+uXHd2W43UoTdnRDwv8QA2gBQCsizvqGTttbtSlCkLpO8MkGREyM0O3XM8nI0r7K4FN5hIVb38n9lkUCX1O9ALboHSKnl9S9flkz2zrokSFvkkcbWO2wgi2/BIiKwdiIF/MwZcseoy1EkXo4/YUYHNMgU9EPQg5a3Zja3XP4ViLY+VnWgTq1f129ZhiSDWPEYTPdHJxj3g=
  edge: true 
script:
  - sleep 25
  - echo 'OK'
