#language: ruby
#addons:
#  apt:
#    packages:
#    - cmake
#    - time

#script:
#  - sleep 25
#  - echo 'OK'
language: ruby
#services:
#  - postgresql
#before_script:
#  - psql -c 'create database travis_ci_test;' -U postgres
#env:
#  global:
#    - secure: PPC38ppzVbEUxEp9JgQLhqQTt9LbZ+PhAbSgqqGl02uSqCbp1EYGun8YG1pAtYY4oBbpOX/9tC9Z55oztBWWA8FHmlPLB3w4npSZzwNjXxcBrlWQ9Hv4W1jCO7ZJxQvOOD9WbblyfJqNWvzZG5OIzdr36oAusPiYPnE3LgSYEHdtjK4Xj4fHyJX3lYY4TZVSGNhNV5Jt9muSVMspplSMLujpNQY7mG4hoILR5K64SNoE6uYXG43Mbhs6ZVPU1SzUB+xqh9hWpvE+RlaSQuDRvZxhyPH5BpkWNEsQrVutPoAcqoiZHUmjHeoXvCf9kcla4URpERwxB5YO3BYW/a5bYEk0HDC9VLy1EmH4NsePj4K5QMliT1QHJ2+tfmTVhPkNlI2jQnP8a6173+fJ5EuvaOjrCY+l4pqUIIBSLOuMdXn8yXKMUlxF7qk/SlnNis8NJWT2Vpa/GxsGseYx8aPWcolEXj7jdC8K8Jc9gdvaPMRaoQx2IDg7FUeAeEL/NmZ42Voidt9cQqzwtmHTO7ezjBrwMNb69URIpx+H7g6ZSnVhftSBcU1lM5THfUIga3JqElOt+Tv0VjySsqYdH39l4zcwV6TPnjnggqpIgRu6NNJD/60HUrOIp6fyvHkp8WrS/kGTVWI/1iZJ+dZdi+TBDzKRLtRriZqLKtOtAg54cOc=
deploy:
  provider: pages:git
  token: QVDEtEs3GM8BUnzpPcUqFFk5+Gd3ix1L60T6gSfnmJQlpi8vbmbJe2yrVw0lWnNldRlAq+HqLZh2zL3LeqlVdWv4jhhoDJLaOBtLUloAF81Q8LuDFPfW/QJPrJVIrBj/XUffJ4N0xhc9erd5yX+UZaoA0MaInA6O1XXYV6gKs0YY+w7nvBmDkF+7VLfTEDUYsp/I+7Rvcq5A6G2FgHOb9ynBQFoYG6q1DZAvnd4qEUI+ijcu8px0REpcj6cikOhojQvjdc1RHly7ka0dTSNfTS5iK289WMQ37UVlEEZ0V0VwWQ3mHyqXLxfWewecX5wVwi0eBgRbuUjOjdFRYsmFszumZyC0yEkSBdvEO546VjMcO2bnnSgjiJ0LA/Er/9JA6pFOjVyTjaiY/fekqpoCMIDD7bSOwrt2I1UuzWzLewwyrXm6HHi3qtwmT87q+31pNw1Ppe1S7oTFCSyjVNiYCFhSfiLHo8nezglPGumJrPYgtYVoXnCOKeJX/zwaJRsRxzrWba1L8SbRdQdSAkBX58BhFKbAJRAh3BJY3vuRN9tuK6TAiHkkOKynVfQRlcYPmFEkgLUGnyOYs5m8VffrnhqQSjYjbaO7aZZ3GQGvizlTRK3Fp8gTg8/qd8Putzj20Bm/h4YpMqwLcpIZTjQjTlodlgz0naAHfyrhDrN6ZM0=
  skip_cleanup: true
script:
  - sleep 25
  - echo 'OK'
