#language: ruby
#addons:
#  apt:
#    packages:
#    - cmake
#    - time

#script:
#  - sleep 25
#  - echo 'OK'
language: ruby
#services:
#  - postgresql
#before_script:
#  - psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
    - secure: PPC38ppzVbEUxEp9JgQLhqQTt9LbZ+PhAbSgqqGl02uSqCbp1EYGun8YG1pAtYY4oBbpOX/9tC9Z55oztBWWA8FHmlPLB3w4npSZzwNjXxcBrlWQ9Hv4W1jCO7ZJxQvOOD9WbblyfJqNWvzZG5OIzdr36oAusPiYPnE3LgSYEHdtjK4Xj4fHyJX3lYY4TZVSGNhNV5Jt9muSVMspplSMLujpNQY7mG4hoILR5K64SNoE6uYXG43Mbhs6ZVPU1SzUB+xqh9hWpvE+RlaSQuDRvZxhyPH5BpkWNEsQrVutPoAcqoiZHUmjHeoXvCf9kcla4URpERwxB5YO3BYW/a5bYEk0HDC9VLy1EmH4NsePj4K5QMliT1QHJ2+tfmTVhPkNlI2jQnP8a6173+fJ5EuvaOjrCY+l4pqUIIBSLOuMdXn8yXKMUlxF7qk/SlnNis8NJWT2Vpa/GxsGseYx8aPWcolEXj7jdC8K8Jc9gdvaPMRaoQx2IDg7FUeAeEL/NmZ42Voidt9cQqzwtmHTO7ezjBrwMNb69URIpx+H7g6ZSnVhftSBcU1lM5THfUIga3JqElOt+Tv0VjySsqYdH39l4zcwV6TPnjnggqpIgRu6NNJD/60HUrOIp6fyvHkp8WrS/kGTVWI/1iZJ+dZdi+TBDzKRLtRriZqLKtOtAg54cOc=
deploy:
  provider: pages:git
  token: HqX9G5HhDUlmRNyyBq/JP3j6G0Vc6pXldveH4UtkNnFEQRcEwuvqqAWJvCEzTO9p0jNlsMJKk8eaqLRbikzqrWitvcJwo6OaXq80wwEV0Fpk4D4nAie2xjsQ5JmkXM/RFLmaaOxHyyR/kZdGyc0U3ypqU6rnhk3ldWihlRwA18J8/k3VKF9ki6C2L3StiZI4un7WBSI0CeuaweSiABtsiVOU+vR8XZnvHKtnQq7M0tM8hNWTgl1bL3jIeEY2usrb7J9CS9VLiQL4zqunYMddPzQ3TH4qf+NGFa6ru2Sicq+GFJ9gi9IVupAyWdYqLJ2y+xd+xXwgTyRSY2lCk+EjNhiTSkEw8lExrC4oYkJXM9Ftjy+dhINWN7zf6o+2XU/FDLT5wXbFK2nIVa16Y+B/lNfTdxHcmoB++UxTH7yj4S0kQt8Mxbro9gGQQe9T9yFPMRD1yehszEfipKT/7aLJWaexAmiODOZ2/JFhmb7rqu0lVq2+h9k8x5MFMajRgSAt1lcvaT3GT6SATEouP++fxR01AfrSd71DP/hhylq7sqa0xm78ViX3morRdaHL98PEYMI7bbbfAhnxAEbC14JbxlWRG2zEk6TTzpXV/FdYLBPp6pSjN8E9KGKfjSIiuYvqrOOf9jA/eRPyE1rcnnXslY9X/afEmvK0NJB2yei1zXI=
  edge: true 
script:
  - sleep 25
  - echo 'OK'
